In [1]:
import _init_paths
import os, sys
import numpy as np
import pprint
from tictactoe import TicTacToe
from tictactoe import Player

In [2]:
pp = pprint.PrettyPrinter(indent=4)

In [3]:
tictac = TicTacToe()
tictac.load('data/tictac_final.txt')

In [4]:
tictac.eval_classifier('lsvm')

(0.508421052631579, array([[ 0.40483382,  0.31825525],
        [ 0.81570995,  0.56381261]], dtype=float32))

In [5]:
tictac.eval_classifier('knn')

(0.448421052631579, array([[ 0.6737805 ,  0.17202573],
        [ 1.27134144,  0.32958201]], dtype=float32))

In [6]:
tictac.eval_classifier('mlp')

(0.46210526315789469, array([[ 0.45757577,  0.28870967],
        [ 1.0060606 ,  0.46451613]], dtype=float32))

In [7]:
tictac.load('data/tictac_single.txt')

In [8]:
a,m = tictac.eval_classifier('lsvm')
np.savetxt('lsvm.txt', m, fmt='%.4f %.4f %.4f %.4f %.4f %.4f %.4f %.4f %.4f')
print a

0.236946564885


In [9]:
a,m = tictac.eval_classifier('knn')
np.savetxt('test.txt', m, fmt='%.4f %.4f %.4f %.4f %.4f %.4f %.4f %.4f %.4f')
print a

0.63786259542


In [10]:
a,m = tictac.eval_classifier('mlp')
np.savetxt('test.txt', m, fmt='%.4f %.4f %.4f %.4f %.4f %.4f %.4f %.4f %.4f')
print a

0.714198473282


In [16]:
tictac.load('data/tictac_multi.txt')

In [17]:
tictac.eval_regressor('knn')

0.90234096692111954

In [18]:
tictac.eval_regressor('mlp')

0.90212044105173883

In [19]:
tictac.eval_regressor('lin')

0.78205258693808322

In [2]:
p = Player()

In [3]:
p.set_regressor_method('mlp')
p.set_classifier_method('mlp')
p.agent.load('data/tictac_multi.txt')
p.agent.train()

In [4]:
p.run()

Game on
Please take a step:4
Current state:
[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]]
Please take a step:2
Current state:
[[-1.  0.  1.]
 [ 0.  1.  0.]
 [-1.  0.  0.]]
Please take a step:3
Current state:
[[-1.  0.  1.]
 [ 1.  1.  0.]
 [-1.  0. -1.]]
Please take a step:5
Game over
Final state:
[[-1.  0.  1.]
 [ 1.  1.  1.]
 [-1.  0. -1.]]
You win!
